name: backend_testing_workflow

on:
  push:
    branches:
      - 'development'
    paths:
      - 'src/data/**'
      - 'src/models/**'
  
jobs:
  api-testing:
    name: Backend testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9.16
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.16"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test the backend with pytest
        run: |
          pytest ./src/tests/test_dataset_code.py
          pytest ./src/tests/test_model.py
          pytest src/api/test_server.py